# Generated by Django 2.2.3 on 2019-07-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('parent_dept_id', models.CharField(max_length=64, verbose_name='上级部门编号')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_num', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='员工编号')),
                ('full_name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('work_phone', models.CharField(max_length=20, verbose_name='办公电话')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('holidays_name', models.CharField(max_length=20, verbose_name='假期名称')),
                ('is_legal_holidays', models.BooleanField(default=False, verbose_name='是否法定节假日')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=10, verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('head', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('level', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.TextField(max_length=255, verbose_name='假单编号')),
                ('leave_type', models.TextField(max_length=100, verbose_name='假别')),
                ('ask_time', models.DateField(blank=True, verbose_name='请假时间')),
                ('report_back_time', models.DateField(blank=True, null=True, verbose_name='销假时间')),
                ('start_time', models.DateField(blank=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, verbose_name='结束时间')),
                ('reason', models.TextField(default='无', max_length=500, verbose_name='请假原因')),
                ('destination', models.TextField(max_length=100, null=True, verbose_name='目的地')),
                ('approval_id', models.TextField(max_length=255, verbose_name='审批单编号')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType', verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='Signingin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_leave', models.BooleanField(default=False)),
                ('detail', models.TextField(default='无')),
                ('leave_count', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
