# Generated by Django 2.2.3 on 2019-08-05 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('parent_dept_id', models.CharField(max_length=64, verbose_name='上级部门编号')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_num', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='员工编号')),
                ('full_name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性别')),
                ('birth_date', models.DateField(null=True, verbose_name='出生日期')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('work_phone', models.CharField(max_length=20, verbose_name='办公电话')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EveryDayArrangements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('weekday', models.IntegerField(verbose_name='星期')),
                ('is_workday', models.BooleanField(default=False, verbose_name='是工作日')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='是否节假日')),
                ('is_legal_holiday', models.BooleanField(default=False, verbose_name='是否法定节假日')),
                ('holiday_name', models.TextField(blank=True, default='', max_length=100, verbose_name='节假日名称')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='假期名称')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='假别')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, verbose_name='假期名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=10, verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='工作时间制度名称')),
                ('shift', models.TextField(max_length=20, verbose_name='班次')),
                ('start_time', models.TimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, verbose_name='结束时间')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Signingin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='时长')),
                ('is_auto_signout', models.BooleanField(default=False, verbose_name='是否系统自动签退')),
                ('is_come_late', models.BooleanField(default=False, verbose_name='是否迟到')),
                ('is_left_early', models.BooleanField(default=False, verbose_name='是否早退')),
                ('is_legal_holiday', models.BooleanField(default=False, verbose_name='是否节日加班')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='是否加班')),
                ('is_night', models.BooleanField(default=False, verbose_name='是否夜班')),
                ('reason', models.TextField(default='', max_length=500, verbose_name='原因')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('head', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('level', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_time', models.DateTimeField(blank=True, verbose_name='请假时间')),
                ('report_back_time', models.DateTimeField(blank=True, null=True, verbose_name='销假时间')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('reason', models.TextField(default='无', max_length=500, verbose_name='请假原因')),
                ('destination', models.TextField(max_length=100, null=True, verbose_name='目的地')),
                ('leave_id', models.TextField(max_length=255, verbose_name='假单编号')),
                ('approval_id', models.TextField(max_length=255, verbose_name='审批单编号')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LeaveType', verbose_name='假别')),
            ],
            options={
                'ordering': ['ask_time'],
            },
        ),
        migrations.CreateModel(
            name='HolidayArrangements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_legal_holiday', models.BooleanField(default=False, verbose_name='是否法定节假日')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HolidayName', verbose_name='假期名称')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType', verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('state', models.TextField(default='出勤', max_length=20, verbose_name='考勤状态')),
                ('is_night_work_overtime', models.BooleanField(default=False, verbose_name='是否夜加班')),
                ('is_work_overtime', models.BooleanField(default=False, verbose_name='是否加班')),
                ('is_legal_holiday', models.BooleanField(default=False, verbose_name='是否法定节假日加班')),
                ('is_leave', models.BooleanField(default=False, verbose_name='是否休假')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee', verbose_name='员工')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WorkTime', verbose_name='班次')),
            ],
        ),
    ]
