# Generated by Django 2.2.3 on 2019-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
    ]
