# Generated by Django 2.2.4 on 2019-08-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_work_overtime',
            new_name='is_holiday_work_overtime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_legal_holiday',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_absenteeism',
            field=models.BooleanField(default=False, verbose_name='是否旷工'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_attendance',
            field=models.BooleanField(default=False, verbose_name='是否正常出勤'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_come_late',
            field=models.BooleanField(default=False, verbose_name='是否迟到'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_left_early',
            field=models.BooleanField(default=False, verbose_name='是否早退'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_legal_holiday_work_overtime',
            field=models.BooleanField(default=False, verbose_name='是否节日加班'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False, verbose_name='是否请假'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_night_work_overtime',
            field=models.BooleanField(default=False, verbose_name='是否加夜班'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(max_length=20, verbose_name='班次'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(default='出勤', max_length=20, verbose_name='考勤状态'),
        ),
    ]
