# Generated by Django 2.2.3 on 2019-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190723_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Signingin',
            name='detail',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='Signingin',
            name='leave_count',
            field=models.IntegerField(default=0, verbose_name='请假天数'),
        ),
    ]
