# Generated by Django 2.2.3 on 2019-08-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='名称')),
                ('type', models.CharField(choices=[('firm', '公司'), ('department', '部门')], default='department', max_length=20, verbose_name='类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Structure', verbose_name='父类架构')),
            ],
            options={
                'verbose_name': '组织架构',
                'verbose_name_plural': '组织架构',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/%Y/%m'),
        ),
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='employee',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee', verbose_name='上级主管'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Structure', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='holidayname',
            name='name',
            field=models.TextField(max_length=20, verbose_name='节假日名称'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
