# Generated by Django 2.2.3 on 2019-07-24 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190724_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOvertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='signingin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='signingin',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='signingin',
            name='is_leave',
        ),
        migrations.RemoveField(
            model_name='signingin',
            name='leave_count',
        ),
        migrations.AlterField(
            model_name='signingin',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='signingin',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签退时间'),
        ),
        migrations.AlterField(
            model_name='signingin',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到时间'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_leave', models.BooleanField(default=False)),
                ('detail', models.TextField(default='无', verbose_name='备注')),
                ('leave_count', models.IntegerField(default=0, verbose_name='请假天数')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
