# Generated by Django 2.2.3 on 2019-07-28 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190724_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['ask_time']},
        ),
        migrations.AddField(
            model_name='workovertime',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='时长'),
        ),
        migrations.AddField(
            model_name='workovertime',
            name='employee',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workovertime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签退时间'),
        ),
        migrations.AddField(
            model_name='workovertime',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到时间'),
        ),
    ]
