# Generated by Django 2.2.3 on 2019-07-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190728_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayArrangements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_legal_holidays', models.BooleanField(default=False, verbose_name='是否法定节假日')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='假期名称')),
                ('remarks', models.TextField(default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='工作时间制度名称')),
                ('shift', models.TextField(max_length=20, verbose_name='班次')),
                ('start_time', models.TimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, verbose_name='结束时间')),
                ('remarks', models.TextField(default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='remarks',
            field=models.TextField(default='', max_length=100, verbose_name='假期名称'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='detail',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='holidayarrangements',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HolidayName', verbose_name='假期名称'),
        ),
    ]
