# Generated by Django 2.2.3 on 2019-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190729_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayname',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
    ]
