# Generated by Django 2.2.3 on 2019-07-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190729_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='假期名称'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
    ]
