# Generated by Django 2.2.3 on 2019-07-30 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190729_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='detail',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='holidayarrangements',
            old_name='is_legal_holidays',
            new_name='is_legal_holiday',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leave_count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_legal_holiday',
            field=models.BooleanField(default=False, verbose_name='是否法定节假日加班'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_night_work_overtime',
            field=models.BooleanField(default=False, verbose_name='是否夜加班'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_work_overtime',
            field=models.BooleanField(default=False, verbose_name='是否加班'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.WorkTime', verbose_name='班次'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='state',
            field=models.TextField(default='出勤', max_length=20, verbose_name='考勤状态'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False, verbose_name='是否休假'),
        ),
    ]
