# Generated by Django 2.2.3 on 2019-07-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190730_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayarrangements',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='leave',
            name='ask_time',
            field=models.DateTimeField(blank=True, verbose_name='请假时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='report_back_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='销假时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_time',
            field=models.DateTimeField(blank=True, verbose_name='开始时间'),
        ),
    ]
