# Generated by Django 2.2.3 on 2019-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190731_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayArrangements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_workday', models.BooleanField(default=False, verbose_name='是工作日')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='是否节假日')),
                ('is_legal_holiday', models.BooleanField(default=False, verbose_name='是否法定节假日')),
                ('holiday_name', models.TextField(blank=True, default='', max_length=100, verbose_name='节假日名称')),
                ('remarks', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
        ),
    ]
