# Generated by Django 2.2.3 on 2019-08-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_workdayarrangements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkDayArrangements',
            new_name='EveryDayArrangements',
        ),
    ]
