# Generated by Django 2.2.3 on 2019-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190804_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydayarrangements',
            name='weekday',
            field=models.IntegerField(default=0, verbose_name='星期'),
            preserve_default=False,
        ),
    ]
