# Generated by Django 2.2.3 on 2019-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_everydayarrangements_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingin',
            name='remarks',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
