# Generated by Django 2.2.3 on 2019-08-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_signingin_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingin',
            name='is_auto_signout',
            field=models.BooleanField(default=False, verbose_name='是否系统自动签退'),
        ),
    ]
